name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cabal: ["3.8"]
        # no ghc-7.10.3 available
        ghc:
          - "8.0.2"
          - "8.2.2"
          - "8.4.4"
          - "8.6.5"
          - "8.8.4"
          - "8.10.7"
          - "9.0.2"
          - "9.2.8"
          - "9.4.8"
        include:
          - ghc: "9.6.6"
            cabal: "3.10"
          - ghc: "9.8.4"
            cabal: "3.10"
          - ghc: "9.10.1"
            cabal: "3.10"
          - ghc: "9.12.1"
            cabal: "3.14"
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal v2-update
      - run: cabal v2-freeze
      - uses: actions/cache@v4
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal v2-build all
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        cabal: ["3.8"]
        # choco install ghc --version 7.10.3 is broken
        ghc:
          - "7.10.3.2"
          - "8.0.2"
          - "8.2.2"
          - "8.4.4"
          - "8.6.5"
          - "8.8.4"
          - "8.10.7"
        winio: [false]
        include:
          - ghc: "9.0.2"
            cabal: "3.8"
            winio: true
          - ghc: "9.2.8"
            cabal: "3.8"
            winio: true
          - ghc: "9.4.8"
            cabal: "3.8"
            winio: true
          - ghc: "9.6.6"
            cabal: "3.10"
            winio: true
          - ghc: "9.8.4"
            cabal: "3.10"
            winio: true
          - ghc: "9.10.1"
            cabal: "3.10"
            winio: true
          - ghc: "9.12.1"
            cabal: "3.14"
            winio: true
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal v2-update
      - run: cabal v2-freeze
      - uses: actions/cache@v4
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal v2-build all
      - if: matrix.winio
        run: cabal v2-build all --ghc-option=-with-rtsopts=--io-manager=native
